# Generated by Django 5.0.7 on 2024-07-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(upload_to=''),
        ),
    ]
