# Generated by Django 5.0.7 on 2024-07-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0003_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_size',
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
