# Generated by Django 5.0.7 on 2024-07-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0004_rename_file_data_file_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(),
        ),
    ]
