# Generated by Django 5.0.7 on 2024-07-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0005_alter_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
