# Generated by Django 5.0.7 on 2024-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0006_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
