# Generated by Django 5.0.7 on 2024-07-20 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0007_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared',
            name='url',
        ),
        migrations.AddField(
            model_name='shared',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
