# Generated by Django 5.0.7 on 2024-07-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0009_alter_shared_access_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
